title: Plateer GitLab Insights
description: Plateer GitLab Insights

# Development server config, needed to load some of the content
webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Theme settings
site_author: Carlos Pereira Atencio
repo_url: 'https://github.com/iceTeamRepo/iceTeamRepo.github.io'
edit_on_github: true
github_docs_folder: false
sticky_navigation: true
prev_next_buttons_location: both
search_enabled: true
hljs_style: github-gist
